
SELECT 
    CN_SALGE.SAL_ANOP,
    CN_SALGE.SAL_MESP,
	CN_SALGE.CUE_CONT,
    MAX(CN_CUENT.CUE_NATU)CUE_NATU,
    ARB_CECO,ARB_PROY,
    ARB_AREA,ARB_SUCU,
    MAX(CN_CUENT.CUE_TSEP) CUE_TSEP, 
    SUM(SCE_VADB)SCE_VADB,
    SUM(SCE_VACR)SCE_VACR,
    0 SAL_VPRE,
    0 SAL_MOVI,
    0 SAL_TRAS,
    0 SAL_VRES 
FROM 
    CN_SALGE,
    CN_CUENT,
    GN_ARBOL GN_CECOS,
    GN_ARBOL GN_PROYE,
    GN_ARBOL GN_AREAS,
    GN_ARBOL GN_SUCUR
WHERE 1=1
    AND CN_SALGE.EMP_CODI = CN_CUENT.EMP_CODI 
    AND CN_SALGE.CUE_CONT = CN_CUENT.CUE_CONT 
    AND CN_CUENT.CUE_MAPR = 'S' 
    AND CN_SALGE.EMP_CODI = 231 
    AND CN_SALGE.SAL_ANOP = 2020 									--> AÑO 
    AND CN_SALGE.SAL_MESP BETWEEN 1 			AND 6 				--> RANGO DE MESES 
    AND CN_CUENT.CUE_CODI BETWEEN '6209020303' 	AND '6209020303' 	--> CUENTA CONTABLE 
    AND CN_SALGE.EMP_CODI = GN_CECOS.EMP_CODI 	
	AND CN_SALGE.ARB_CECO = GN_CECOS.ARB_CONT 
    AND GN_CECOS.ARB_CODI BETWEEN '03020102' 	AND '03020102'  	--> CENTRO DE COSTO 
    AND CN_SALGE.EMP_CODI = GN_PROYE.EMP_CODI 	
	AND CN_SALGE.ARB_PROY = GN_PROYE.ARB_CONT 
    AND GN_PROYE.ARB_CODI BETWEEN '10140101' 	AND '10140101' 		--> PROYECTO 
    AND CN_SALGE.EMP_CODI = GN_AREAS.EMP_CODI 
	AND CN_SALGE.ARB_AREA = GN_AREAS.ARB_CONT 
    AND GN_AREAS.ARB_CODI BETWEEN '05' 			AND '05' 			--> AREA 
    AND CN_SALGE.EMP_CODI = GN_SUCUR.EMP_CODI 
	AND CN_SALGE.ARB_SUCU = GN_SUCUR.ARB_CONT 
    AND GN_SUCUR.ARB_CODI BETWEEN '010101' 		AND '010101' 		-->SUCURSAL 
GROUP BY CN_SALGE.SAL_ANOP,CN_SALGE.SAL_MESP,CN_SALGE.CUE_CONT,ARB_CECO,ARB_PROY,ARB_AREA,ARB_SUCU 

UNION 

SELECT 
    PF_SALDO.SAL_ANOP,
	PF_SALDO.SAL_MESP,
	PF_SALDO.CUE_CONT,
    MAX(CUE_NATU) CUE_NATU,
    ARB_CECO,
    ARB_PROY,
    ARB_AREA,
    ARB_SUCU,
    MAX(CN_CUENT.CUE_TSEP) CUE_TSEP, 
    0 SCE_VADB,
    0 SCE_VACR,
    SUM(SAL_VPRE)SAL_VPRE,
    SUM(SAL_VADI-SAL_VRED) SAL_MOVI,
    SUM(SAL_VTRS-SAL_VTRR) SAL_TRAS,
    SUM(SAL_VRES) SAL_VRES 
FROM 
    PF_SALDO,
    CN_CUENT,
    GN_ARBOL GN_CECOS,
    GN_ARBOL GN_PROYE,
    GN_ARBOL GN_AREAS,
    GN_ARBOL GN_SUCUR 
WHERE 1=1
    AND PF_SALDO.EMP_CODI = CN_CUENT.EMP_CODI 
    AND PF_SALDO.CUE_CONT = CN_CUENT.CUE_CONT 
    AND PF_SALDO.EMP_CODI = 231 
    AND PF_SALDO.SAL_ANOP = 2020 -->AÑO 
    AND PF_SALDO.SAL_MESP BETWEEN 1 			AND 6 				-->RANGO DE MESES 
    AND CN_CUENT.CUE_CODI BETWEEN '6209020303' 	AND '6209020303' 	--> CUENTA CONTABLE 
    AND PF_SALDO.EMP_CODI = GN_CECOS.EMP_CODI 
    AND PF_SALDO.ARB_CECO = GN_CECOS.ARB_CONT 
    AND GN_CECOS.ARB_CODI BETWEEN '03020102' 	AND '03020102' 		--> CENTRO DE COSTO 
    AND PF_SALDO.EMP_CODI = GN_PROYE.EMP_CODI 
    AND PF_SALDO.ARB_PROY = GN_PROYE.ARB_CONT 
    AND GN_PROYE.ARB_CODI BETWEEN '10140101' 	AND '10140101' 		--> PROYECTO 
    AND PF_SALDO.EMP_CODI = GN_AREAS.EMP_CODI 
    AND PF_SALDO.ARB_AREA = GN_AREAS.ARB_CONT 
    AND GN_AREAS.ARB_CODI BETWEEN '05' 			AND '05' 			--> AREA 
    AND PF_SALDO.EMP_CODI = GN_SUCUR.EMP_CODI 
    AND PF_SALDO.ARB_SUCU = GN_SUCUR.ARB_CONT 
    AND GN_SUCUR.ARB_CODI BETWEEN '010101' 		AND '010101' 		--> SUCURSAL 
GROUP BY PF_SALDO.SAL_ANOP,PF_SALDO.SAL_MESP,PF_SALDO.CUE_CONT,ARB_CECO,ARB_PROY,ARB_AREA,ARB_SUCU